# Generated by Django 6.0.3 on 2026-03-12 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('skills_required', models.CharField(blank=True, help_text='Optional. Example: Python, Django, DRF, PostgreSQL', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'), models.Index(fields=['is_active'], name='projects_pr_is_acti_f7dee7_idx'), models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'), models.Index(fields=['deadline'], name='projects_pr_deadlin_bd2912_idx'), models.Index(fields=['client'], name='projects_pr_client__06571b_idx'), models.Index(fields=['client', 'status'], name='projects_pr_client__60b095_idx')],
            },
        ),
    ]
