# Generated by Django 6.0.3 on 2026-03-11 10:04

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, help_text='Optional. Must be unique if provided.', max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Optional. Must be unique if provided.', max_length=20, null=True, unique=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('reset_password', 'Reset password'), ('change_password', 'Change password'), ('verify_email', 'Verify email'), ('verify_phone', 'Verify phone')], max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='new', max_length=10)),
                ('target', models.CharField(help_text='Email address or phone number where the code was sent.', max_length=255)),
                ('code', models.CharField(help_text='Verification code. Usually 4-6 digits.', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='accounts_us_phone_n_613c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['target'], name='accounts_ve_target_95bba0_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['channel'], name='accounts_ve_channel_a8bde4_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['purpose'], name='accounts_ve_purpose_98a644_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['status'], name='accounts_ve_status_ff43d7_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['created_at'], name='accounts_ve_created_fafc92_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['expires_at'], name='accounts_ve_expires_861e49_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'purpose'], name='accounts_ve_user_id_2b1aef_idx'),
        ),
    ]
