# Generated by Django 6.0.3 on 2026-03-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='user_images/default.png', null=True, upload_to='user_images/'),
        ),
    ]
