# Generated by Django 6.0.3 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="user_images/default.jpg",
                null=True,
                upload_to="user_images/",
            ),
        ),
    ]
