# Generated by Django 6.0.3 on 2026-03-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.TextField(help_text="Freelancer's offer message for the project.")),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_time_days', models.PositiveIntegerField(help_text='Estimated number of days to complete the work.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_bids', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='bids_bid_status_071bbe_idx'), models.Index(fields=['created_at'], name='bids_bid_created_3cd9ec_idx'), models.Index(fields=['project'], name='bids_bid_project_7740dd_idx'), models.Index(fields=['freelancer'], name='bids_bid_freelan_cbb8b3_idx'), models.Index(fields=['project', 'status'], name='bids_bid_project_1702f0_idx'), models.Index(fields=['freelancer', 'status'], name='bids_bid_freelan_ad7d2a_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'freelancer'), name='unique_bid_per_project_per_freelancer')],
            },
        ),
    ]
